version: '3'

services:

  mysql-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scholarx
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  scholarx-app:
    image: scholarx
    depends_on:
      - mysql-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=scholarx
      - DATABASE_PORT=3306
    labels:
      kompose.image-pull-policy: "Never"

  auth-server:
    image: auth-server 
    depends_on: 
      - mysql-db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=scholarx
      - DATABASE_PORT=3306
    labels:
      kompose.image-pull-policy: "Never"
